
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEDIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMES\n    expression : term\n               | expression PLUS term\n               | expression MINUS term\n    \n    term : factor\n         | term TIMES factor\n         | term DIVIDE factor\n    factor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'NUMBER':([0,5,6,7,8,9,],[4,4,4,4,4,4,]),'LPAREN':([0,5,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,4,11,12,13,14,15,],[0,-1,-4,-7,-2,-3,-5,-6,-8,]),'PLUS':([1,2,3,4,10,11,12,13,14,15,],[6,-1,-4,-7,6,-2,-3,-5,-6,-8,]),'MINUS':([1,2,3,4,10,11,12,13,14,15,],[7,-1,-4,-7,7,-2,-3,-5,-6,-8,]),'RPAREN':([2,3,4,10,11,12,13,14,15,],[-1,-4,-7,15,-2,-3,-5,-6,-8,]),'TIMES':([2,3,4,11,12,13,14,15,],[8,-4,-7,8,8,-5,-6,-8,]),'DIVIDE':([2,3,4,11,12,13,14,15,],[9,-4,-7,9,9,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,],[1,10,]),'term':([0,5,6,7,],[2,2,11,12,]),'factor':([0,5,6,7,8,9,],[3,3,3,3,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> term','expression',1,'p_expression','PlyExample.py',60),
  ('expression -> expression PLUS term','expression',3,'p_expression','PlyExample.py',61),
  ('expression -> expression MINUS term','expression',3,'p_expression','PlyExample.py',62),
  ('term -> factor','term',1,'p_term','PlyExample.py',73),
  ('term -> term TIMES factor','term',3,'p_term','PlyExample.py',74),
  ('term -> term DIVIDE factor','term',3,'p_term','PlyExample.py',75),
  ('factor -> NUMBER','factor',1,'p_factor_num','PlyExample.py',90),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','PlyExample.py',94),
]
